apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus-1
  name: girus-1
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
